version: "3.5"

services:
  db:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 8080:8080
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: unless-stopped

volumes:
  postgres:
